### ISSUE TITLE
As the AI categorizer is present there seems to be it fork to categorize transaction from this app

### ISSUE THREAD

**Issue by makp0** [sudores/firefly-iii-bank-sync#1]
https://github.com/sudores/firefly-iii-bank-sync#:~:text=As%20the%20AI%20categorizer%20is%20present%20there%20seems%20to%20be%20it%20fork%20to%20categorize%20transaction%20from%20this%20app

Could you, please, elaborate?

**Comment by sudores** [comment]
@makp0 
There was a plan to make a patch for firefly-iii AI categorization ([link](https://github.com/bahuma20/firefly-iii-ai-categorize)) to get transaction category and possibly tags depending on it's description and notes.
It was assumed as there're some info like MCC, IBAN in `notes` field it could make results more accurate. But I still had no chance to test it. 
There're 2 solutions present, as I know, which could be used to categorize transactions. So if you've willing to test them out with synced transaction - you're welcome. (:
ffiitc - [link](https://github.com/bahuma20/firefly-iii-ai-categorize)
firefly-iii-ai-categorize - [link](https://github.com/bahuma20/firefly-iii-ai-categorize)
